<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // List of athletic clubs
        $clubs = [
            'Alex Wasps Athletic Club',
            'Alpha Athletic Club',
            'Amanzimtoti Athletic Club',
            'Ama-Ravens Athletics Club',
            'Ashley Athletic Club',
            'Balele Athletics Club',
            'Bayview Striders Athletic Club',
            'Beacon Willie Mtolo Athletics Club',
            'Berea Rovers Athletic Club',
            'Bergville Athletics Club',
            'Biggarsberg Athletics Club',
            'Bluff Athletic Club',
            'Born 2 Run Athletic Club',
            'Carbineers Athletic Club',
            'Checkstar Falcons Athletic Club',
            'Chesterville Athletic Club',
            'Chiltern Athletic Club',
            'Crusaders Running Club',
            'Dolphin Coast Striders',
            'Drakensburg Athletic Club',
            'Duguza Athletic Club',
            'Durban Athletic Club',
            'Durban City Multisport Club',
            'Durban Collegians Athletic Club',
            'Durban Defence Athletic Club',
            'Durban Heroes Athletic Club',
            'Durban High School Old Boys AC',
            'Durban Ramblers Athletic Club',
            'Durban Runner Athletic Club',
            'Duzi Athletic Club',
            'East Griqualand Striders',
            'Edgewood Athletic Club',
            'eDumbe Athletics Club',
            'eMadadeni Athletic Club',
            'Emnambithi Striders',
            'Empangeni Athletic Club',
            'Emtshezi Development Athletic Club',
            'Engen Athletic Club – KZN',
            'Eskom Athletic Club - KZN',
            'Eskom Gijimas – KZN',
            'Estcourt Athletic Club',
            'Estcourt Vultures Athletic Club',
            'Ezakheni Athletic Club',
            'Fezela Athletic Club',
            'Fire Athletic Club',
            'First National Runners – KZN',
            'Folweni Athletics Club',
            'Forest Hills Athletic Club',
            'Formula 1 Athletic Club',
            'Gallopers Athletic Club',
            'Genius Athletic Club',
            'Getfit Athletic Club',
            'Groove Athletic Club',
            'Groutville Athletic Club',
            'Harmony Athletic Club – KZN',
            'Highway Athletic Club',
            'Hillcrest Villagers Athletics Club',
            'Hiltonians Athletic Club',
            'Hluhluwe Athletic Club',
            'Howick Athletic Club',
            'Hulamin Athletic Club',
            'Hulett Aluminium Athletic Club – KZN',
            'Ikhwezi Athletic Club',
            'Imamba Athletic Club',
            'Impendle Athletic Club',
            'Indumiso Athletic Club',
            'Inkamana Athletics Club – KZN',
            'Ixopo Athletic Club',
            'Jabulani Athletic Club',
            'Joy Athletic Club',
            'Jules Athletic Club',
            'Kearsney Striders',
            'King Fisher Athletic Club',
            'Kosi Bay Athletic Club',
            'Kwamashu Athletic Club',
            'Kwa-Mashu Athletic Club',
            'Kwadengezi Athletic Club',
            'KZN Military AC',
            'Ladysmith Athletics Club',
            'Lamontville Athletic Club',
            'Liberty Life Athletic Club – KZN',
            'Liberty Nike Athletic Club',
            'M L Sultan Athletic Club',
            'Mamba Athletic Club',
            'Manguzi Athletics Club',
            'Maritzburg Striders',
            'Mayibuyi Athletic Club',
            'Merewent Athletic Club',
            'Metro Athletic Club',
            'Midlands Athletic Club',
            'Mittal Athletic Club – Newcastle',
            'Mount Currie Athletic Club',
            'Mount Edgecombe Villagers Athletic Club',
            'Mr Price Athletic Club – KZN',
            'Mtubatuba Athletic Club',
            'Mtunzini Athletic Club',
            'Muden Athletic Club',
            'Nashua Richards Bay Athletic Club',
            'Natal Carbineers Athletic Club',
            'Natal University Athletic Club – PMB',
            'Nation Athletic Club',
            'Nedbank Running Club Kwazulu-Natal – Durban',
            'Nerve Events & Durban Athletic Club',
            'New Balance Athletics North',
            'Newcastle City Athletic Club',
            'Newcastle Harriers Club',
            'Newlands Athletic Club',
            'Newlands Striders',
            'Nkandla Athletic Club',
            'Northern Athletic Club',
            'Ntunjambilli Athletic Club',
            'Nxamalala Striders Athletic Club',
            'Ogwini Comprehensive Athletic Club',
            'Osizweni Athletic Club',
            'Owabahle Athletics Club',
            'Phantane Athletic Club',
            'Phoenix Striders Athletic Club',
            'Phuma Athletic Club',
            'Pietermaritzburg Athletic Club',
            'Pilgrims Runners Club',
            'Pinetown & Districts Athletic Club',
            'Pinetown Old Boys’ Athletic Club',
            'Pongola Athletic Club',
            'Power Athletic Club',
            'Qalakahle Athletic Club',
            'Queensburgh Harriers',
            'Rainbow Chicken Farms Athletic Club – KZN',
            'Redro Harriers',
            'Reservoir Hills Athletic Club',
            'Richmond Athletic Club',
            'Rising Sun Chatsworth Athletic Club',
            'Run for Fun Athletic Club',
            'Run/Walk for Life Athletic Club',
            'SA Police AC - PMB',
            'SA Police Athletic Club – Durban',
            'Saints Athletic Club',
            'Sani Athletic Club',
            'SAPS Striders Athletic Club',
            'Savages Athletic Club',
            'Save Orion Athletic Club',
            'Scottburgh Athletic Club',
            'Shallcross Athletic Club',
            'Sharks Athletic Club',
            'Siyaphambili Athletic Club',
            'Siyaphila Athletics Club',
            'South Coast Striders',
            'Spartan Athletics Club – KZN',
            'Steadville Athletic Club',
            'Stela Athletic Club',
            'Stonebridge Athletic Club',
            'Technikon Natal Athletic Club',
            'Telkom Athletic Club – Natal',
            'Titan Athletic Club – KZN',
            'Tongaat Panthers',
            'Toti Athletic Club',
            'Toti Walkers Athletic Club',
            'Transnet AAC – Natal',
            'Transwerk Stonebridge Athletic Club',
            'Trojane Baan & Veld Atletiekklub',
            'Twini Athletic Club',
            'Ubunye Athletic Club',
            'Ulundi Athletics Club',
            'Umbumbulu Coll AC',
            'uMhlathuze Athletic Club',
            'uMlazi Athletic Club',
            'uMqulusi Athletic Club',
            'Umvoti Athletic Club',
            'Umzinto Athletic Club',
            'Verulam Athletic Club',
            'Vryheid Athletic Club',
            'Vultures Athletic Club – KZN',
            'Westville Athletic Club',
            'Wings Athletic Club',
            'Woodview Athletic Club',
            'Yellowwood Park Athletics Club',
            'Zabalaza Athletic Club'
        ];

        // Create each club as a category
        foreach ($clubs as $club) {
            Category::create([
                'name' => $club,
                'category_type' => Category::CATEGORY_TYPE_CLUB,
                'location' => null,  // You can add club locations here if available
            ]);
        }
    }
}
